/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package supermartket.ui.comp;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.text.DecimalFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingWorker;
import supermartket.dao.dto.ItemProductAnalysisAndReportingDTO;

/**
 *
 * @author hanguyen
 */
public class ItemProductAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form ItemProductAnalysis
     * @param item
     */
    public ItemProductAnalysis(ItemProductAnalysisAndReportingDTO item) {
        initComponents();
        DecimalFormat df = new DecimalFormat("#,##0.00");
        txtSold.setText(String.valueOf(item.getQuantitySold()) + " đã bán");
        txtTotalAmount.setText(df.format(item.getTotalRevenue()) + "đ");
        txtProductName.setText(String.valueOf(item.getProductName()));
        loadImageAsync(txtProductImage, item.getProductImage(), 45, 45);
    }

    private void loadImageAsync(JLabel label, String imageUrl, int w, int h) {
        new SwingWorker<ImageIcon, Void>() {
            @Override
            protected ImageIcon doInBackground() throws Exception {
                URL url = new URL(imageUrl);
                BufferedImage img = ImageIO.read(url); // nhanh hơn new ImageIcon(url)
                if (img != null) {
                    Image scaled = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
                    return new ImageIcon(scaled);
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    ImageIcon icon = get();
                    if (icon != null) {
                        label.setIcon(icon);
                    } else {
                        label.setText("Không tải được ảnh");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    label.setText("Không tải được ảnh");
                }
            }
        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        txtProductImage = new javax.swing.JLabel();
        txtProductName = new javax.swing.JLabel();
        txtSold = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JLabel();

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        txtProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtProductName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProductName.setText("Coca Cola 330ml");

        txtSold.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSold.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSold.setText("81 đã bán");

        txtTotalAmount.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTotalAmount.setText("12,892,932đ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProductName)
                .addGap(18, 18, 18))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtSold)
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(txtTotalAmount)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel txtProductImage;
    private javax.swing.JLabel txtProductName;
    private javax.swing.JLabel txtSold;
    private javax.swing.JLabel txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
