/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package supermartket.ui.manager;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import supermartket.dao.CreateProductCategoryListener;
import supermartket.dao.ProductCategoryDAO;
import supermartket.dao.ProductCategoryListener;
import supermartket.dao.impl.ProductCategoryDAOImpl;
import supermartket.entity.ProductCategory;
import supermartket.ui.comp.ProductCategoryItem;
import supermartket.ui.form.CreateProductCategoryJDialog;

public class Category extends javax.swing.JPanel {

    ProductCategoryDAO dao = new ProductCategoryDAOImpl();

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        List<ProductCategory> categories = dao.findAll();
        loadCards(categories);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        introduce = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        pnlCategories = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1098, 829));

        main.setPreferredSize(new java.awt.Dimension(1098, 829));

        introduce.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel9.setText("Quản lý loại sản phẩm");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Phân loại và tổ chức sản phẩm");

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermartket/icons/icons8-plus-24.png"))); // NOI18N
        btnCreate.setText("Thêm loại sản phẩm");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introduceLayout = new javax.swing.GroupLayout(introduce);
        introduce.setLayout(introduceLayout);
        introduceLayout.setHorizontalGroup(
            introduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introduceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(introduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
        );
        introduceLayout.setVerticalGroup(
            introduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introduceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(introduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCategories.setLayout(new java.awt.GridLayout(0, 3, 20, 20));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(pnlCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(pnlCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 618, Short.MAX_VALUE))
        );

        btnSearch.setText("Lọc");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(introduce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(introduce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateProductCategoryJDialog createProductCategory = new CreateProductCategoryJDialog((Frame) SwingUtilities.getWindowAncestor(this), true, new CreateProductCategoryListener() {
            @Override
            public void onCreate(ProductCategory category) {
                ProductCategory newCategory = dao.create(category);
                createCategory(createButton(newCategory));
            }
        });
        createProductCategory.setLocationRelativeTo(null);
        createProductCategory.setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        List<ProductCategory> categories = dao.findAllByName(txtSearch.getText().trim());
        loadCards(categories);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void loadCards(List<ProductCategory> categories) {
        mainPanel.removeAll();
        pnlCategories.removeAll();
        pnlCategories.setLayout(new BorderLayout());
        JPanel pnlGrid = new JPanel();
        pnlGrid.setLayout(new GridLayout(0, 3, 20, 20));
        categories.forEach(card -> pnlGrid.add(this.createButton(card)));
        int itemHeight = 170;
        int rows = (int) Math.ceil(categories.size() / 3.0);
        int totalHeight = rows * (itemHeight + 20);
        pnlGrid.setPreferredSize(new Dimension(0, totalHeight));
        pnlCategories.add(pnlGrid, BorderLayout.NORTH);
        JScrollPane scrollPane = new JScrollPane(pnlCategories);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(scrollPane, BorderLayout.CENTER);
        pnlCategories.setBorder(null);
        mainPanel.setBorder(null);
        pnlCategories.revalidate();
        pnlCategories.repaint();
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    private JPanel createButton(ProductCategory category) { // tạo Jbutton cho thẻ 
        ProductCategoryItem cateItem = new ProductCategoryItem(this, category, new ProductCategoryListener() {
            @Override
            public void onDelete(ProductCategoryItem categoryItem) {
                deleteCategory(categoryItem);
            }

            @Override
            public void onUpdate(ProductCategoryItem categoryItem, ProductCategory item) {
                updateCategory(categoryItem, item);
            }
        });
        cateItem.setPreferredSize(new Dimension(0, 80));
        cateItem.setName(category.getCategoryID());
        return cateItem;
    }

    public void updateCategory(JPanel panel, ProductCategory card) {
        JPanel parentPanel = (JPanel) pnlCategories.getComponent(0);

        for (int i = 0; i < parentPanel.getComponentCount(); i++) {
            Component comp = parentPanel.getComponent(i);

            if (comp.getName() != null && comp.getName().equals(panel.getName())) {

                panel.setName(card.getCategoryID());

                parentPanel.remove(i);
                parentPanel.add(this.createButton(card), i);

                parentPanel.revalidate();
                parentPanel.repaint();
                return;
            }
        }

    }

    public void deleteCategory(JPanel panel) {
        if (pnlCategories.getComponentCount() > 0) {
            JPanel parentPanel = (JPanel) pnlCategories.getComponent(0);
            parentPanel.remove(panel);
            parentPanel.revalidate();
            parentPanel.repaint();
        }
    }

    public void createCategory(JPanel panel) {
        if (pnlCategories.getComponentCount() > 0) {
            JPanel parentPanel = (JPanel) pnlCategories.getComponent(0);
            parentPanel.add(panel);
            parentPanel.revalidate();
            parentPanel.repaint();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel introduce;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlCategories;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
